interface YIF_DBM_JET_CONSTANTS
  public .


  constants GC_CRDT_I type TABNAM value 'Ydbe_CRDT_LMT_I' ##NO_TEXT.
  constants GC_CRDT_EXMPT type TABNAME16 value 'YdbeC_CRDT_EXMPT' ##NO_TEXT.
  constants GC_CRDT_H type TABNAME16 value 'YdbeC_CRDT_LMT_H' ##NO_TEXT.
  constants GC_MSG_CLASS_ID type ARBGB value 'YMSG_JET_dbe' ##NO_TEXT.
  constants GC_VALUE_E type SY-MSGTY value 'E' ##NO_TEXT.
  constants GC_VALUE_W type SY-MSGTY value 'W' ##NO_TEXT.
  constants GC_VALUE_U type CHAR1 value 'U' ##NO_TEXT.
  constants GC_VALUE_A type SY-MSGTY value 'A' ##NO_TEXT.
  constants GC_VALUE_I type SY-MSGTY value 'I' ##NO_TEXT.
  constants GC_VALUE_S type SY-MSGTY value 'S' ##NO_TEXT.
  constants GC_PH_TXT type TEXT5 value 'Ph: ' ##NO_TEXT.
  constants GC_EID_TXT type TEXT5 value 'Eid: ' ##NO_TEXT.
  constants GC_TDOBJECT type CHAR10 value 'dbe_O_HDR' ##NO_TEXT.
  constants GC_VALUE_H type CHAR1 value 'H' ##NO_TEXT.
  constants GC_MOBILIT type CHAR5 value '0003' ##NO_TEXT.
  constants GC_HEADTXT type CHAR5 value '0001' ##NO_TEXT.
  constants GC_DBE_VEH_BATCH_ACTIVATE type CVLC03-AKTION value 'ZBAT' ##NO_TEXT.
  constants GC_DBM_VEH_BATCH_ACTIVATE type CVLC03-AKTION value 'ZBAT' ##NO_TEXT.
  constants GC_DBE_VEH_PO_CREATE_ACTION type CVLC03-AKTION value 'QORD' ##NO_TEXT.
  constants GC_DBM_VEH_PO_CREATE_ACTION type CVLC03-AKTION value 'QORD' ##NO_TEXT.
  constants GC_DBE_VEH_PO_UPDATE_ACTION type CVLC03-AKTION value 'QMOR' ##NO_TEXT.
  constants GC_DBM_VEH_PO_UPDATE_ACTION type CVLC03-AKTION value 'QMOR' ##NO_TEXT.
  constants GC_VMS_VEH_PO_CREATE_ACTION type CVLC03-AKTION value 'ORD1' ##NO_TEXT.
  constants GC_VMS_VEH_PO_UPDATE_ACTION type CVLC03-AKTION value 'MORD' ##NO_TEXT.
  constants GC_VMS_VEH_CUST_ASSIGN_ACTION type CVLC03-AKTION value 'QACU' ##NO_TEXT.
  constants GC_DBM_VEH_UPDATE_ACTION type CVLC03-AKTION value 'QMOD' ##NO_TEXT.
  constants GC_DBE_VEH_UPDATE_ACTION type CVLC03-AKTION value 'QMOD' ##NO_TEXT.
  constants GC_DBE_ORG1 type EKORG value '2100' ##NO_TEXT.
  constants GC_DBM_ORG1 type EKORG value '2100' ##NO_TEXT.
  constants GC_DBM_ORG2 type EKORG value '2200' ##NO_TEXT.
  constants GC_DBE_ORG2 type EKORG value '2200' ##NO_TEXT.
  constants GC_VMS_ORG type EKORG value '2300' ##NO_TEXT.
  constants GC_LANG_EN type SPRAS value 'EN' ##NO_TEXT.
  constants GC_LANG_AR type SPRAS value 'AR' ##NO_TEXT.
  constants GC_DBM_VEH_PO_CHANGEV_ACTION type CVLC03-AKTION value 'QMOD' ##NO_TEXT.
  constants GC_DBE_VEH_PO_CHANGEV_ACTION type CVLC03-AKTION value 'QMOD' ##NO_TEXT.
  constants GC_DBM_VEH_PO_CREATEV_ACTION type CVLC03-AKTION value 'QCRE' ##NO_TEXT.
  constants GC_DBE_VEH_PO_CREATEV_ACTION type CVLC03-AKTION value 'QCRE' ##NO_TEXT.
  constants GC_DBM_ACTION_QDBM type CVLC03-AKTION value 'QDBM' ##NO_TEXT.
  constants GC_DBE_ACTION_QDBE type CVLC03-AKTION value 'Qdbe' ##NO_TEXT.
  constants GC_DBM_ACTION_CREA type CVLC03-AKTION value 'CREA' ##NO_TEXT.
  constants GC_DBE_ACTION_CREA type CVLC03-AKTION value 'CREA' ##NO_TEXT.
  constants GC_VALUE_EQ type CHAR5 value 'EQ' ##NO_TEXT.
  constants GC_DBM_VEH_INTERN_OR_ACTION type CVLC03-AKTION value 'QIOG' ##NO_TEXT.
  constants GC_DBE_VEH_INTERN_OR_ACTION type CVLC03-AKTION value 'QIOG' ##NO_TEXT.
  constants GC_DBE_VEH_ZMOD type CVLC03-AKTION value 'ZMOD' ##NO_TEXT.
  constants GC_DBM_VEH_ZMOD type CVLC03-AKTION value 'ZMOD' ##NO_TEXT.
  constants GC_DBM_VEH_CRMV_ACTION type CVLC03-AKTION value 'CRMV' ##NO_TEXT.
  constants GC_DBE_VEH_CRMV_ACTION type CVLC03-AKTION value 'CRMV' ##NO_TEXT.
  constants GC_DBM_VEH_QCRV type CVLC03-AKTION value 'QCRV' ##NO_TEXT.
  constants GC_DBE_VEH_QCRV type CVLC03-AKTION value 'QCRV' ##NO_TEXT.
  constants GC_DBE_VEH_ZCOM type CVLC03-AKTION value 'ZCOM' ##NO_TEXT.
  constants GC_DBM_VEH_ZCOM type CVLC03-AKTION value 'ZCOM' ##NO_TEXT.
  constants GC_SAPVENDOR_TYPE type CHAR6 value 'FLVN01' ##NO_TEXT.
  constants GC_SAPCUSTOMER_TYPE type CHAR6 value 'FLCU01' ##NO_TEXT.
  constants GC_VALUE_BT type CHAR2 value 'BT' ##NO_TEXT.
  constants GC_VMAKE_MB type /DBE/VEH_V_MAKE value 'MB' ##NO_TEXT.
  constants GC_VMAKE_BMW type /DBE/VEH_V_MAKE value 'BW' ##NO_TEXT.
  constants GC_VMAKE_AUDI type /DBE/VEH_V_MAKE value 'AD' ##NO_TEXT.
  constants GC_VMAKE_LEXUS type /DBE/VEH_V_MAKE value 'LX' ##NO_TEXT.
  constants GC_DBE_BUSTYPE_CUS type /DBE/BUSTYPE value 'CUS' ##NO_TEXT.
  constants GC_DBM_BUSTYPE_CUS type /DBE/BUSTYPE value 'CUS' ##NO_TEXT.
  constants GC_DBE_BUSTYPE_USC type /DBE/BUSTYPE value 'USC' ##NO_TEXT.
  constants GC_DBM_BUSTYPE_USC type /DBE/BUSTYPE value 'USC' ##NO_TEXT.
  constants GC_VEHICLE_AVAIL_AV type VLC_AVAILABILITY value 'AV' ##NO_TEXT.
  constants GC_VEH_QOIV type CVLC03-AKTION value 'QOIV' ##NO_TEXT.
  constants GC_YES type CHAR3 value 'YES' ##NO_TEXT.
  constants GC_NO type CHAR2 value 'NO' ##NO_TEXT.
  constants GC_TRADEIN_ACTION_QCLT type CVLC03-AKTION value 'QCLT' ##NO_TEXT.
  constants GC_VEH_QGOR type CVLC03-AKTION value 'QGOR' ##NO_TEXT.
  constants GC_VEH_QGIS type CVLC03-AKTION value 'QGIS' ##NO_TEXT.
  constants GC_VEHI_CONDITION_GROSS type KSCHA value 'QSML' ##NO_TEXT.
  constants GC_VEHI_CONDITION_COST type KSCHA value 'QPRS' ##NO_TEXT.
  constants GC_VEHI_CONDITION_SUPPORT type KSCHA value 'YJDS' ##NO_TEXT.
  constants GC_PPC_PO_GRN_NO type BWART value '101' ##NO_TEXT.
  constants GC_FEATURE_CAT_COLOR type CHAR3 value 'CLR' ##NO_TEXT.
  constants GC_FEATURE_CAT_UPHOISTRY type CHAR3 value 'UPH' ##NO_TEXT.
  constants GC_FEATURE_CAT_STANDARD type CHAR3 value 'STD' ##NO_TEXT.
  constants GC_FEATURE_CAT_MODEL_TYPE type CHAR3 value 'YMO' ##NO_TEXT.
  constants GC_FEATURE_CAT_INT_COLOR type CHAR3 value 'UPH' ##NO_TEXT.
  constants GC_FEATURE_CAT_EXT_COLOR type CHAR3 value 'CLR' ##NO_TEXT.
  constants GC_FEATURE_CAT_FEATURE1 type CHAR3 value 'OPT' ##NO_TEXT.
  constants GC_FEATURE_CAT_FEATURE2 type CHAR3 value 'OPT' ##NO_TEXT.
  constants GC_FEATURE_CAT_FEATURE3 type CHAR3 value 'OPT' ##NO_TEXT.
  constants GC_TRANSMISSION type CHAR4 value 'TRNM' ##NO_TEXT.
  constants GC_VEHI_MATERIAL_TYPE type MTART value 'VEHI' ##NO_TEXT.
  constants GC_VEHI_CORR type VLC_ACTION value 'CORR' ##NO_TEXT.
  constants GC_VEHI_QP30 type VLC_MMSTATU value 'QP30' ##NO_TEXT.
  constants GC_VEHI_QP40 type VLC_MMSTATU value 'QP40' ##NO_TEXT.
  constants GC_VEHI_ZJD1 type VLC_CNTRL value 'ZJD1' ##NO_TEXT.
  constants GC_NAI_PLANT type WERKS_D value '2341' ##NO_TEXT.
  constants GC_PRIC_CNTRL_INDICATOR_S type VPRSV value 'S' ##NO_TEXT.
  constants GC_VEHI_COLOR_CONFIG_NAME type NAME_KOMP value 'VEHICLE_COLOR_KEY' ##NO_TEXT.
  constants GC_VEHI_UPH_CONFIG_NAME type NAME_KOMP value 'VEHICLE_UPH_KEY' ##NO_TEXT.
  constants GC_VEHI_STD_CONFIG_NAME type NAME_KOMP value 'VEHICLE_STD_KEY' ##NO_TEXT.
  constants GC_VEHI_TRNSM_CONFIG_NAME type NAME_KOMP value 'VEHICLE_TRNSM_KEY' ##NO_TEXT.
  constants GC_VEHI_MODEL_CONFIG_NAME type NAME_KOMP value 'VEHICLE_MODEL_KEY' ##NO_TEXT.
  constants GC_VEHI_INT_CLR_CONFIG_NAME type NAME_KOMP value 'VEHICLE_INT_CLR_KEY' ##NO_TEXT.
  constants GC_VEHI_EXT_CLR_CONFIG_NAME type NAME_KOMP value 'VEHICLE_EXT_CLR_KEY' ##NO_TEXT.
  constants GC_VEHI_FEATURE1_CONFIG_NAME type NAME_KOMP value 'VEHICLE_FEATR1_KEY' ##NO_TEXT.
  constants GC_VEHI_FEATURE2_CONFIG_NAME type NAME_KOMP value 'VEHICLE_FEATR2_KEY' ##NO_TEXT.
  constants GC_VEHI_FEATURE3_CONFIG_NAME type NAME_KOMP value 'VEHICLE_FEATR3_KEY' ##NO_TEXT.
  constants GC_VEHI_ZKGR type VLC_ACTION value 'ZKGR' ##NO_TEXT.
  constants GC_VEHI_ZKID type VLC_ACTION value 'ZKID' ##NO_TEXT.
  constants GC_VEHI_ZGWS type VLC_ACTION value 'ZGWS' ##NO_TEXT.
  constants GC_VALUE_D type CHAR1 value 'D' ##NO_TEXT.
  constants GC_VALUE_SW type CHAR2 value 'SW' ##NO_TEXT.
  constants GC_VALUE_SE type CHAR2 value 'SE' ##NO_TEXT.
  constants GC_VALUE_EE type CHAR2 value 'EE' ##NO_TEXT.
  constants GC_YJST type BSART value 'YJST' ##NO_TEXT.
  constants GC_YPI0 type BSART value 'YPIO' ##NO_TEXT.
  constants GC_BAUMASTER type CHAR3 value 'YBM' ##NO_TEXT.
  constants GC_EXT_CLR type CHAR3 value 'YCL' ##NO_TEXT.
  constants GC_ENGINE type CHAR3 value 'YEN' ##NO_TEXT.
  constants GC_RIMS type CHAR3 value 'YRM' ##NO_TEXT.
  constants GC_P003 type CHAR4 value 'P003' ##NO_TEXT.
  constants GC_OPT_EQ type CHAR3 value 'YOE' ##NO_TEXT.
  constants GC_CMN type CHAR5 value 'Z_CMN' ##NO_TEXT.
  constants GC_SAR type FCURR_CURR value 'SAR' ##NO_TEXT.
  constants GC_USD type FCURR_CURR value 'USD' ##NO_TEXT.
  constants GC_VEHI_QP60 type VLC_MMSTATU value 'QP60' ##NO_TEXT.
  constants GC_VEHICLE_AVAIL_YD type VLC_AVAILABILITY value 'YD' ##NO_TEXT.
  constants GC_VEHI_CONDITION_YJDD type KSCHA value 'YJDD' ##NO_TEXT.
  constants GC_PPC_PO_GRN_NO_102 type BWART value '102' ##NO_TEXT.
  constants GC_VEHI_ZKPO type VLC_ACTION value 'ZKPO' ##NO_TEXT.
  constants GC_VEHI_ZSTD type VLC_ACTION value 'ZSTD' ##NO_TEXT.
  constants GC_SAPVENDOR1 type LIFNR value '6200000000' ##NO_TEXT.
  constants GC_NAI_BUKRS type BUKRS value '2300' ##NO_TEXT.
  constants GC_JC_BUKRS type BUKRS value '2100' ##NO_TEXT.
  constants GC_JP_BUKRS type BUKRS value '2200' ##NO_TEXT.
  constants GC_VEHI_QRPO type KSCHA value 'QRPO' ##NO_TEXT.
  constants GC_VEHI_YJD3 type KSCHA value 'YJD3' ##NO_TEXT.
  constants GC_VEHI_YJD2 type KSCHA value 'YJD2' ##NO_TEXT.
  constants GC_VEHI_YJD4 type KSCHA value 'YJD4' ##NO_TEXT.
  constants GC_ZREP_SLOC type LGORT_D value 'V001' ##NO_TEXT.
  constants GC_ZREP_PLANT type WERKS_D value '2290' ##NO_TEXT.
  constants GC_UB type BSART value 'UB' ##NO_TEXT.
  constants GC_QCUO type CVLC03-AKTION value 'QCUO' ##NO_TEXT.
  constants GC_QS30 type VLC_MMSTATU value 'QS30' ##NO_TEXT.
  constants GC_DBM_BUSTYPE_NEC type /DBE/BUSTYPE value 'NEC' ##NO_TEXT.
  constants GC_DBE_BUSTYPE_NEC type /DBE/BUSTYPE value 'NEC' ##NO_TEXT.
  constants GC_JP_SPART_JACO1 type SPART value 'A1' ##NO_TEXT.
  constants GC_JP_SPART_FUSO1 type SPART value 'C3' ##NO_TEXT.
  constants GC_NAI_VCLASS type BKLAS value '2305' ##NO_TEXT.
  constants GC_NAI_CLASSNUM type CLASS value 'YAUTO_BATCH' ##NO_TEXT.
  constants GC_PRIC_CNTRL_INDICATOR_V type VPRSV value 'V' ##NO_TEXT.
  constants GC_PTERM_Z001 type DZTERM value 'Z001' ##NO_TEXT.
  constants GC_PTERM_Z055 type DZTERM value 'Z055' ##NO_TEXT.
endinterface.
