*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDBE_VEHI_MASS_PROCESSINGTOP.     " Global Data
  INCLUDE LZDBE_VEHI_MASS_PROCESSINGUXX.     " Function Modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /DBE/LVEHI_MASS_PROCESSINGF...     " Subroutines
* INCLUDE /DBE/LVEHI_MASS_PROCESSINGO...     " PBO-Modules
* INCLUDE /DBE/LVEHI_MASS_PROCESSINGI...     " PAI-Modules
* INCLUDE /DBE/LVEHI_MASS_PROCESSINGE...     " Events
* INCLUDE /DBE/LVEHI_MASS_PROCESSINGP...     " Local class implement.
*  INCLUDE /DBE/LVEHI_MASS_PROCESSING_CON.
INCLUDE LZDBE_VEHI_MASS_PROCESSINGO01.
*  INCLUDE /DBE/lvehi_mass_processingo01.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO02.
*  INCLUDE /DBE/lvehi_mass_processingo02.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO03.
*  INCLUDE /DBE/lvehi_mass_processingo03.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI01.
*  INCLUDE /DBE/lvehi_mass_processingi01.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO04.
*  INCLUDE /DBE/lvehi_mass_processingo04.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO05.
*  INCLUDE /DBE/lvehi_mass_processingo05.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF03.
*  INCLUDE /DBE/lvehi_mass_processingf03.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO06.
*  INCLUDE /DBE/lvehi_mass_processingo06.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF04.
*  INCLUDE /DBE/lvehi_mass_processingf04.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO07.
*  INCLUDE /DBE/lvehi_mass_processingo07.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF05.
*  INCLUDE /DBE/lvehi_mass_processingf05.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO08.
*  INCLUDE /DBE/lvehi_mass_processingo08.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF06.
*  INCLUDE /DBE/lvehi_mass_processingf06.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO09.
*  INCLUDE /DBE/lvehi_mass_processingo09.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF07.
*  INCLUDE /DBE/lvehi_mass_processingf07.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF08.
*  INCLUDE /DBE/lvehi_mass_processingf08.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF09.
*  INCLUDE /DBE/lvehi_mass_processingf09.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF12.
*  INCLUDE /DBE/lvehi_mass_processingf12.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF13.
*  INCLUDE /DBE/lvehi_mass_processingf13.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO10.
*  INCLUDE /DBE/lvehi_mass_processingo10.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI02.
*  INCLUDE /DBE/lvehi_mass_processingi02.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO11.
*  INCLUDE /DBE/lvehi_mass_processingo11.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF14.
*  INCLUDE /DBE/lvehi_mass_processingf14.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO12.
*  INCLUDE /DBE/lvehi_mass_processingo12.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO13.
*  INCLUDE /DBE/lvehi_mass_processingo13.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO14.
*  INCLUDE /DBE/lvehi_mass_processingo14.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI04.
*  INCLUDE /DBE/lvehi_mass_processingi04.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF15.
*  INCLUDE /DBE/lvehi_mass_processingf15.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI05.
*  INCLUDE /DBE/lvehi_mass_processingi05.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF16.
*  INCLUDE /DBE/lvehi_mass_processingf16.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO15.
*  INCLUDE /DBE/lvehi_mass_processingo15.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF17.
*  INCLUDE /DBE/lvehi_mass_processingf17.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI06.
*  INCLUDE /DBE/lvehi_mass_processingi06.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF18.
*  INCLUDE /DBE/lvehi_mass_processingf18.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI07.
*  INCLUDE /DBE/lvehi_mass_processingi07.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF20.
*  INCLUDE /DBE/lvehi_mass_processingf20.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI08.
*  INCLUDE /DBE/lvehi_mass_processingi08.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF21.
*  INCLUDE /DBE/lvehi_mass_processingf21.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI09.
*  INCLUDE /DBE/lvehi_mass_processingi09.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI10.
*  INCLUDE /DBE/lvehi_mass_processingi10.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF22.
*  INCLUDE /DBE/lvehi_mass_processingf22.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF23.
*  INCLUDE /DBE/lvehi_mass_processingf23.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI11.
*  INCLUDE /DBE/lvehi_mass_processingi11.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI12.
*  INCLUDE /DBE/lvehi_mass_processingi12.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF19.
*  INCLUDE /DBE/lvehi_mass_processingf19.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI13.
*  INCLUDE /DBE/lvehi_mass_processingi13.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF24.
*  INCLUDE /DBE/lvehi_mass_processingf24.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGP01.
*  INCLUDE /DBE/lvehi_mass_processingp01.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGP02.
*  INCLUDE /DBE/lvehi_mass_processingp02.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF25.
*  INCLUDE /DBE/lvehi_mass_processingf25.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF26.
*  INCLUDE /DBE/lvehi_mass_processingf26.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF27.
*  INCLUDE /DBE/lvehi_mass_processingf27.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO16.
*  INCLUDE /DBE/lvehi_mass_processingo16.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO17.
*  INCLUDE /DBE/lvehi_mass_processingo17.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF01.
*  INCLUDE /DBE/lvehi_mass_processingf01.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF02.
*  INCLUDE /DBE/lvehi_mass_processingf02.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF10.
*  INCLUDE /DBE/lvehi_mass_processingf10.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO18.
*  INCLUDE /DBE/lvehi_mass_processingo18.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI14.
*  INCLUDE /DBE/lvehi_mass_processingi14.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF11.
*  INCLUDE /DBE/lvehi_mass_processingf11.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI15.
*  INCLUDE /DBE/lvehi_mass_processingi15.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF28.
*  INCLUDE /DBE/lvehi_mass_processingf28.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGP03.
*  INCLUDE /DBE/lvehi_mass_processingp03.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGP04.
*  INCLUDE /DBE/lvehi_mass_processingp04.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGP05.
*  INCLUDE /DBE/lvehi_mass_processingp05.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO19.
*  INCLUDE /DBE/lvehi_mass_processingo19.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF29.
*  INCLUDE /DBE/lvehi_mass_processingf29.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF30.
*  INCLUDE /DBE/lvehi_mass_processingf30.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF31.
*  INCLUDE /DBE/lvehi_mass_processingf31.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF32.
*  INCLUDE /DBE/lvehi_mass_processingf32.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI16.
*  INCLUDE /DBE/lvehi_mass_processingi16.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI17.
*  INCLUDE /DBE/lvehi_mass_processingi17.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF33.
*  INCLUDE /DBE/lvehi_mass_processingf33.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI18.
*  INCLUDE /DBE/lvehi_mass_processingi18.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI19.
*  INCLUDE /DBE/lvehi_mass_processingi19.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF34.
*  INCLUDE /DBE/lvehi_mass_processingf34.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF35.
*  INCLUDE /DBE/lvehi_mass_processingf35.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO20.
*  INCLUDE /DBE/lvehi_mass_processingo20.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF36.
*  INCLUDE /DBE/lvehi_mass_processingf36.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF37.
*  INCLUDE /DBE/lvehi_mass_processingf37.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO21.
*  INCLUDE /DBE/lvehi_mass_processingo21.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO22.
*  INCLUDE /DBE/lvehi_mass_processingo22.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF38.
*  INCLUDE /DBE/lvehi_mass_processingf38.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF39.
*  INCLUDE /DBE/lvehi_mass_processingf39.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO23.
*  INCLUDE /DBE/lvehi_mass_processingo23.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI20.
*  INCLUDE /DBE/lvehi_mass_processingi20.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO24.
*  INCLUDE /DBE/lvehi_mass_processingo24.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI21.
*  INCLUDE /DBE/lvehi_mass_processingi21.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF40.
*  INCLUDE /DBE/lvehi_mass_processingf40.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO25.
*  INCLUDE /DBE/lvehi_mass_processingo25.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO26.
*  INCLUDE /DBE/lvehi_mass_processingo26.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI22.
*  INCLUDE /DBE/lvehi_mass_processingi22.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI23.
*  INCLUDE /DBE/lvehi_mass_processingi23.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI24.
*  INCLUDE /DBE/lvehi_mass_processingi24.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF41.
*  INCLUDE /DBE/lvehi_mass_processingf41.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI25.
*  INCLUDE /DBE/lvehi_mass_processingi25.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO27.
*  INCLUDE /DBE/lvehi_mass_processingo27.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF42.
*  INCLUDE /DBE/lvehi_mass_processingf42.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGCL1.
*  INCLUDE /DBE/lvehi_mass_processingcl1.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF43.
*  INCLUDE /DBE/lvehi_mass_processingf43.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO28.
*  INCLUDE /DBE/lvehi_mass_processingo28.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF44.
*  INCLUDE /DBE/lvehi_mass_processingf44.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO29.
*  INCLUDE /DBE/lvehi_mass_processingo29.


INCLUDE LZDBE_VEHI_MASS_PROCESSINGF45.
*  INCLUDE /DBE/lvehi_mass_processingf45.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI26.
*  INCLUDE /DBE/lvehi_mass_processingi26.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI27.
*  INCLUDE /DBE/lvehi_mass_processingi27.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF46.
*  INCLUDE /DBE/lvehi_mass_processingf46.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO30.
*  INCLUDE /DBE/lvehi_mass_processingo30.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF47.
*  INCLUDE /DBE/lvehi_mass_processingf47.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI28.
*  INCLUDE /DBE/lvehi_mass_processingi28.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI29.
*  INCLUDE /DBE/lvehi_mass_processingi29.


INCLUDE LZDBE_VEHI_MASS_PROCESSINGO31.
*  INCLUDE /DBE/lvehi_mass_processingo31.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF50.
*  INCLUDE /DBE/lvehi_mass_processingf50.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI32.
*  INCLUDE /DBE/lvehi_mass_processingi32.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO32.
*  INCLUDE /DBE/lvehi_mass_processingo32.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF52.
*  INCLUDE /DBE/lvehi_mass_processingf52.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI33.
*  INCLUDE /DBE/lvehi_mass_processingi33.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI34.
*  INCLUDE /DBE/lvehi_mass_processingi34.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO33.
*  INCLUDE /DBE/lvehi_mass_processingo33.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO34.
*  INCLUDE /DBE/lvehi_mass_processingo34.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO35.
*  INCLUDE /DBE/lvehi_mass_processingo35.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF53.
*  INCLUDE /DBE/lvehi_mass_processingf53.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO36.
*  INCLUDE /DBE/lvehi_mass_processingo36.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI35.
*  INCLUDE /DBE/lvehi_mass_processingi35.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF54.
*  INCLUDE /DBE/lvehi_mass_processingf54.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI36.
*  INCLUDE /DBE/lvehi_mass_processingi36.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF55.
*  INCLUDE /DBE/lvehi_mass_processingf55.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI37.
*  INCLUDE /DBE/lvehi_mass_processingi37.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF56.
*  INCLUDE /DBE/lvehi_mass_processingf56.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI38.
*  INCLUDE /DBE/lvehi_mass_processingi38.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF57.
*  INCLUDE /DBE/lvehi_mass_processingf57.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI39.
*  INCLUDE /DBE/lvehi_mass_processingi39.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF58.
*  INCLUDE /DBE/lvehi_mass_processingf58.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI40.
*  INCLUDE /DBE/lvehi_mass_processingi40.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF59.
*  INCLUDE /DBE/lvehi_mass_processingf59.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO37.
*  INCLUDE /DBE/lvehi_mass_processingo37.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI41.
*  INCLUDE /DBE/lvehi_mass_processingi41.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF60.
*  INCLUDE /DBE/lvehi_mass_processingf60.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF61.
*  INCLUDE /DBE/lvehi_mass_processingf61.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI42.
*  INCLUDE /DBE/lvehi_mass_processingi42.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF62.
*  INCLUDE /DBE/lvehi_mass_processingf62.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF63.
*  INCLUDE /DBE/lvehi_mass_processingf63.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI43.
*  INCLUDE /DBE/lvehi_mass_processingi43.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI44.
*  INCLUDE /DBE/lvehi_mass_processingi44.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI45.
*  INCLUDE /DBE/lvehi_mass_processingi45.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF64.
*  INCLUDE /DBE/lvehi_mass_processingf64.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGD01.
*  INCLUDE /DBE/lvehi_mass_processingd01.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF65.
*  INCLUDE /DBE/lvehi_mass_processingf65.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI46.
*  INCLUDE /DBE/lvehi_mass_processingi46.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF67.
*  INCLUDE /DBE/lvehi_mass_processingf67.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO38.
*  INCLUDE /DBE/lvehi_mass_processingo38.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF68.
*  INCLUDE /DBE/lvehi_mass_processingf68.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO39.
*  INCLUDE /DBE/lvehi_mass_processingo39.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF69.
*  INCLUDE /DBE/lvehi_mass_processingf69.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF71.
*  INCLUDE /DBE/lvehi_mass_processingf71.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF72.
*  INCLUDE /DBE/lvehi_mass_processingf72.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO40.
*  INCLUDE /DBE/lvehi_mass_processingo40.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF73.
*  INCLUDE /DBE/lvehi_mass_processingf73.

  INCLUDE /DBE/lvehi_mass_processingf79.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO41.
*  INCLUDE /DBE/lvehi_mass_processingo41.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF74.
*  INCLUDE /DBE/lvehi_mass_processingf74.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF75.
*  INCLUDE /DBE/lvehi_mass_processingf75.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF76.
*  INCLUDE /DBE/lvehi_mass_processingf76.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF77.
*  INCLUDE /DBE/lvehi_mass_processingf77.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF78.
*  INCLUDE /DBE/lvehi_mass_processingf78.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF80.
*  INCLUDE /DBE/lvehi_mass_processingf80.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF81.
*  INCLUDE /DBE/lvehi_mass_processingf81.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF82.
*  INCLUDE /DBE/lvehi_mass_processingf82.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF83.
*  INCLUDE /DBE/lvehi_mass_processingf83.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF84.
*  INCLUDE /DBE/lvehi_mass_processingf84.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF85.
*  INCLUDE /DBE/lvehi_mass_processingf85.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI47.
*  INCLUDE /DBE/lvehi_mass_processingi47.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO42.
*  INCLUDE /DBE/lvehi_mass_processingo42.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI48.
*  INCLUDE /DBE/lvehi_mass_processingi48.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF86.
*  INCLUDE /DBE/lvehi_mass_processingf86.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF87.
*  INCLUDE /DBE/lvehi_mass_processingf87.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI49.
*  INCLUDE /DBE/lvehi_mass_processingi49.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI50.
*  INCLUDE /DBE/lvehi_mass_processingi50.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO43.
*  INCLUDE /DBE/lvehi_mass_processingo43.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI51.
*  INCLUDE /DBE/lvehi_mass_processingi51.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF88.
*  INCLUDE /DBE/lvehi_mass_processingf88.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI52.
*  INCLUDE /DBE/lvehi_mass_processingi52.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI53.
*  INCLUDE /DBE/lvehi_mass_processingi53.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI54.
*  INCLUDE /DBE/lvehi_mass_processingi54.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF89.
*  INCLUDE /DBE/lvehi_mass_processingf89.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF90.
*  INCLUDE /DBE/lvehi_mass_processingf90.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO46.
*  INCLUDE /DBE/lvehi_mass_processingo46.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF91.
*  INCLUDE /DBE/LVEHI_MASS_PROCESSINGF91.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF92.
*  INCLUDE /DBE/LVEHI_MASS_PROCESSINGF92.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO44.
*  INCLUDE /DBE/LVEHI_MASS_PROCESSINGO44.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF93.
*  INCLUDE /DBE/LVEHI_MASS_PROCESSINGF93.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI55.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI55.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI56.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI56.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF94.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGF94.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO47.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO47.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF95.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGF95.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO48.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO48.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF96.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGF96.


INCLUDE LZDBE_VEHI_MASS_PROCESSINGI57.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI57.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI58.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI58.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO49.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO49.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI59.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI59.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI60.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI60.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI61.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI61.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF97.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGF97.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO50.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO50.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO51.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO51.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO52.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO52.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI62.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI62.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI63.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI63.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI64.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI64.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF98.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGF98.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGF99.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGF99.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI65.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI65.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI66.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI66.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO53.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO53.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI67.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI67.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI68.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI68.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI69.
*INCLUDE /DBE/lvehi_mass_processingi69.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI70.
*INCLUDE /DBE/lvehi_mass_processingi70.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI71.
*INCLUDE /DBE/lvehi_mass_processingi71.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGR01.
*INCLUDE /DBE/lvehi_mass_processingr01.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO54.
*INCLUDE /DBE/lvehi_mass_processingo54.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI72.
*INCLUDE /DBE/lvehi_mass_processingi72.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO55.
*INCLUDE /DBE/lvehi_mass_processingo55.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI73.
*INCLUDE /DBE/lvehi_mass_processingi73.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI74.
*INCLUDE /DBE/lvehi_mass_processingi74.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO56.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO56.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGR02.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGR02.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI75.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI75.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGR03.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGR03.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGO57.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGO57.

INCLUDE LZDBE_VEHI_MASS_PROCESSINGI76.
*INCLUDE /DBE/LVEHI_MASS_PROCESSINGI76.

INCLUDE lzdbe_vehi_mass_processingo45.

INCLUDE lzdbe_vehi_mass_processingi03.

INCLUDE lzdbe_vehi_mass_processingi30.
