*&---------------------------------------------------------------------*
*& Include          ZIVSS_HONGQI_VEHI_PROCESS_TOP
*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*& Include          ZIVSS_HONGQI_VEHI_INBOUND_TOP
*&---------------------------------------------------------------------*

TYPES : BEGIN OF ty_source_fields,
          ord_no   TYPE char20,
          model    TYPE char20,
          exterior TYPE char20,
          interior TYPE char20,
          company  TYPE char20,
          pur_org  TYPE char20,
          pur_grp  TYPE char20,
          plant    TYPE char20,
          division TYPE char20,
          vendor   TYPE char20,
          yv01     TYPE char20,
          y100     TYPE char20,
          y101     TYPE char20,
          y102     TYPE char20,
          y103     TYPE char20,
          y104     TYPE char20,
          y105     TYPE char20,
          y106     TYPE char20,
          y107     TYPE char20,
          y108     TYPE char20,
          y109     TYPE char20,
          y110     TYPE char20,
          y111     TYPE char20,
          y112     TYPE char20,
          y113     TYPE char20,
        END OF ty_source_fields.
TYPES : BEGIN OF ty_validating_fields,
          ord_no   TYPE char20,
          model    TYPE char20,
          exterior TYPE char20,
          interior TYPE char20,
          company  TYPE char20,
          pur_org  TYPE char20,
          pur_grp  TYPE char20,
          plant    TYPE char20,
          division TYPE char20,
          vendor   TYPE char20,
          yv01     TYPE char20,
          yv01_n   TYPE char20,
          y100     TYPE char20,
          y100_n   TYPE char20,
          y101     TYPE char20,
          y101_n   TYPE char20,
          y102     TYPE char20,
          y102_n   TYPE char20,
          y103     TYPE char20,
          y103_n   TYPE char20,
          y104     TYPE char20,
          y104_n   TYPE char20,
          y105     TYPE char20,
          y105_n   TYPE char20,
          y106     TYPE char20,
          y106_n   TYPE char20,
          y107     TYPE char20,
          y107_n   TYPE char20,
          y108     TYPE char20,
          y108_n   TYPE char20,
          y109     TYPE char20,
          y109_n   TYPE char20,
          y110     TYPE char20,
          y110_n   TYPE char20,
          y111     TYPE char20,
          y111_n   TYPE char20,
          y112     TYPE char20,
          y112_n   TYPE char20,
          y113     TYPE char20,
          y113_n   TYPE char20,
        END OF ty_validating_fields.
TYPES: BEGIN OF ty_veh,
         vguid        TYPE vlcvehicle-vguid,
         vhcle        TYPE vlc_vhcle,
         charg        TYPE charg_d,
         vhvin        TYPE vlc_vhvin,
         vhcex        TYPE vlc_vhcex,
         ebeln        TYPE ebeln,
         ebelp        TYPE ebelp,
         matnr        TYPE matnr,
         zvessel_name TYPE zvessel_name_de,
         zeta_date    TYPE zeta_date_de,
       END OF ty_veh.

TYPES: BEGIN OF ty_po,
         ebeln TYPE ebeln,
         ebelp TYPE ebelp,
       END OF ty_po.
*Log table
TYPES:BEGIN OF ty_log,
        message   TYPE char07,
        vhcex     TYPE vlc_vhcex,
        po        TYPE ebeln,
        po_item   TYPE ebelp,
        long_text TYPE char100.
TYPES:    END OF ty_log.
TYPES: tt_wueb TYPE TABLE OF wueb.
DATA:
  lv_extension     TYPE char03,
  it_source        TYPE TABLE OF ty_source_fields,
  it_lips_temp     TYPE TABLE OF lipsvb,
  it_log           TYPE TABLE OF ty_log,
  it_inb           TYPE TABLE OF bbp_inbd_d,
  it_inb_zbat      TYPE TABLE OF bbp_inbd_d,
  ts_inb           TYPE bbp_inbd_d,
  ts_inb_h         TYPE  bbp_inbd_l,
  va_total_records TYPE char7,
  va_succ_records  TYPE char7,
  va_fail_records  TYPE char7.

CONSTANTS: gc_log     TYPE char03 VALUE 'LOG',
           gc_lgc     TYPE char03 VALUE 'LGC',
           gc_fil     TYPE char03 VALUE 'FIL',
           gc_err     TYPE char01 VALUE 'E',
           gc_abort   TYPE char01 VALUE 'A',
           gc_succ    TYPE char01 VALUE 'S',
           gc_ext1    TYPE char03 VALUE 'CSV',
           gc_ext2    TYPE char03 VALUE 'TXT',
           gc_csv_sep TYPE char01 VALUE ',',
           gc_txt_sep TYPE c VALUE cl_abap_char_utilities=>horizontal_tab,
           gc_error   TYPE char07 VALUE 'Error',##NO_TEXT "Message Code TXT 1700
*           gc_warning TYPE char07 VALUE 'Warning',
           gc_success TYPE char07 VALUE 'Success',
           gc_warning TYPE char07 VALUE 'Warning'.
*Constants for field catalog

CONSTANTS:gc_message     TYPE char25 VALUE 'MESSAGE',
          gc_inbdel      TYPE char25 VALUE 'INBDEL',
          gc_long_text   TYPE char25 VALUE 'LONG_TEXT',
          gc_identifiers TYPE char25 VALUE 'IDENTIFIERS',
          gc_lifnr       TYPE char25 VALUE 'LIFNR',
          gc_verur       TYPE char25 VALUE 'VERUR',
          gc_ebeln       TYPE char25 VALUE 'EBELN',
          gc_ebelp       TYPE char25 VALUE 'EBELP',
          gc_lfdat_la    TYPE char25 VALUE 'LFDAT_LA',
          gc_lfimg       TYPE char25 VALUE 'LFIMG',
          gc_it_source   TYPE char10 VALUE 'IT_SOURCE',
          gc_vhcex       TYPE char25 VALUE 'VHCEX',
          gc_po          TYPE char25 VALUE 'PO',
          gc_po_item     TYPE char25 VALUE 'PO_ITEM'.
