"Name: \TY:CL_FINS_ACDOC_CO_TECH_UTIL\ME:MOVE_AND_CHECK_VALUE_W_MSG\SE:BEGIN\EI
ENHANCEMENT 0 ZVSS_SER_PART_PROFIT.
IF iv_context EQ 'PRCTR'.
  IF iv_source <> cv_target.
    RETURN.
  ENDIF.
ENDIF.
ENDENHANCEMENT.
