"Name: \PR:/DBE/SAPLORDER_UI\FO:F_SCREEN_MOD_ORDER_CREATION\SE:BEGIN\EI
ENHANCEMENT 0 ZVSS_PARTS_VIN_ENHANCEMENT.
 DATA : lv_export(30) TYPE c.
 lv_export = 'X'.
 EXPORT zcash_desk FROM lv_export TO MEMORY ID 'ZPRT_ORD'.
ENDENHANCEMENT.
