"Name: \PR:/DBE/SAPLCO_ACTIONS\FO:READ_DBM_CALL_FLAG\SE:END\EI
ENHANCEMENT 0 ZVSS_VEHI_SETTLEMENT_RULE.
DATA : lv_vss(3) TYPE C.
IMPORT lv_vss FROM MEMORY ID 'YVSS'.
  IF sy-subrc EQ 0.
    cv_dbm_call_flag = 'X'.
  ENDIF.
ENDENHANCEMENT.
