*&---------------------------------------------------------------------*
*& Include          ZVSS_INB_YARD_REP_TOP
*&---------------------------------------------------------------------*
TABLES: likp,  lips, vepvg, vbsk, vbuk, mv50l, vttk, tvst, tpar, rl03t.
TABLES: lipspo,  vekp, t006, lipov, ekko, vbak.

TYPES : BEGIN OF ty_inb,
          vbeln TYPE likp-vbeln,
          lifnr TYPE likp-lifnr,
          vstel TYPE likp-vstel,
          vlstk TYPE likp-vlstk,
          lifex TYPE likp-lifex,
          lfdat TYPE likp-lfdat,
          traid TYPE likp-traid,
          bolnr TYPE likp-bolnr,
          posnr TYPE lips-posnr,
          matnr TYPE lips-matnr,
          lfimg TYPE lips-lfimg,
          meins TYPE lips-meins,
          vgbel TYPE lips-vgbel,
          vgpos TYPE lips-vgpos,
          werks TYPE lips-werks,
          lgort TYPE lips-lgort,
          charg TYPE lips-charg,
          mtart TYPE lips-mtart,
          wbsta TYPE lips-wbsta,
          pksta TYPE lips-pksta,
        END OF ty_inb,
        BEGIN OF ty_po,
          ebeln TYPE ebeln_d,
          ebelp TYPE ebelp,
          menge TYPE bstmg,
          effwr TYPE effwr,
          netwr TYPE effwr,
        END OF ty_po,
        BEGIN OF ty_vbup,
          vbeln TYPE vbeln,
          posnr TYPE posnr,
          wbsta TYPE wbsta,
          pksta TYPE pksta,
        END OF ty_vbup,
        BEGIN OF ty_vehicle,
          vhcle         TYPE vlc_vhcle,
          vhcex         TYPE vlc_vhcex,
          mmsta         TYPE vlc_mmstatu,
          vhvin         TYPE vlc_vhvin,
          /dbe/iobjguid TYPE vlcvehicle-/dbe/iobjguid,
          vguid         TYPE vlcvehicle-vguid,
          zint_color    TYPE ydbm_veh_int_color_de,
          zext_color    TYPE ydbm_veh_ext_color_de,
          division      TYPE spart,
*          zprio_trans TYPE ydbm_veh_prio_trans,
        END OF ty_vehicle,
        BEGIN OF ty_model,
          product_guid TYPE   /dbe/v_imodel-product_guid,
          mcodesd      TYPE /dbe/v_imodel-mcodesd,
          modyear      TYPE /dbe/v_imodel-modyear,
          motext1      TYPE /dbe/v_imodelt-text1,
        END OF ty_model,
        BEGIN OF ty_makt,
          matnr TYPE matnr,
          maktx TYPE maktx,
        END OF ty_makt,
        BEGIN OF ty_output,
          sel        TYPE char1,
          mtart      TYPE lips-mtart,
          vbeln      TYPE likp-vbeln,
          lifnr      TYPE likp-lifnr,
          vstel      TYPE likp-vstel,
          vlstk      TYPE likp-vlstk,
          vlstk_st   TYPE string,
          lifex      TYPE likp-lifex,
          lfdat      TYPE likp-lfdat,
          traid      TYPE likp-traid,
          posnr      TYPE lips-posnr,
          matnr      TYPE lips-matnr,
          maktx      TYPE maktx,
          lfimg      TYPE lips-lfimg,
          meins      TYPE lips-meins,
          vgbel      TYPE lips-vgbel,
          vgpos      TYPE lips-vgpos,
          werks      TYPE lips-werks,
          lgort      TYPE lips-lgort,
          charg      TYPE lips-charg,
          menge      TYPE bstmg,
          balance    TYPE bstmg,
          effwr      TYPE effwr,
          netwr      TYPE netwr,
          wbsta      TYPE wbsta,
          wbsta_st   TYPE string,
          pksta      TYPE pksta,
          pksta_st   TYPE string,
          vhcex      TYPE vlc_vhcex,
          vhvin      TYPE vlc_vhvin,
          vhcle      TYPE vlc_vhcle,
          mmsta      TYPE vlc_mmstatu,
          statut     TYPE vlc_statut,
          mcodesd    TYPE /dbe/v_imodel-mcodesd,
          modyear    TYPE /dbe/v_imodel-modyear,
          motext1    TYPE /dbe/v_imodelt-text1,
          vguid      TYPE vlcvehicle-vguid,
          check      TYPE c,
          qmnum      TYPE qmnum,
          zint_color TYPE ydbm_veh_int_color_de,
          zext_color TYPE ydbm_veh_ext_color_de,
          division   TYPE spart,
          bolnr      TYPE bolnr,
*          zprio_trans TYPE ydbm_veh_prio_trans,
        END OF ty_output,

        BEGIN OF ty_vbuk,
          vbeln TYPE vbeln,
          wbstk TYPE wbstk,
        END OF ty_vbuk,

*        BEGIN OF ty_vbup,
*          vbeln TYPE vbeln,
*          posnr TYPE posnr,
*          wbsta TYPE wbsta,
*        END OF ty_vbup,


        BEGIN OF ty_qmsm,
          qmnum         TYPE qmnum,
          /dbm/demo_veh TYPE vlc_guid,
        END OF ty_qmsm,

        BEGIN OF ty_werks,
          werks TYPE werks_d,
          name1 TYPE name1,
        END OF ty_werks.

DATA : it_inb TYPE TABLE OF ty_inb.
DATA : it_po TYPE TABLE OF ty_po.
DATA : it_vbup TYPE TABLE OF ty_vbup.
DATA : it_vehicle TYPE TABLE OF ty_vehicle.
DATA : it_model TYPE TABLE OF ty_model.
DATA : it_output TYPE TABLE OF ty_output.
DATA : it_makt   TYPE TABLE OF ty_makt,
       it_vbuk   TYPE TABLE OF ty_vbuk,
*       it_vbup      TYPE TABLE OF ty_vbup,
       it_fcat   TYPE slis_t_fieldcat_alv,
       wa_fcat   LIKE LINE OF it_fcat,
       wa_layout TYPE slis_layout_alv,
       lt_qmsm   TYPE STANDARD TABLE OF ty_qmsm,
       ls_qmsm   TYPE ty_qmsm,
*       it_plant_map TYPE TABLE OF ydbmc_plant_comm,
       it_werks  TYPE TABLE OF ty_werks.

DATA : lt_status TYPE STANDARD TABLE OF cvlc02t,
       ls_status TYPE cvlc02t.
