*&---------------------------------------------------------------------*
*& Include          ZVSS_INB_YARD_REP_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK orgdata WITH FRAME TITLE TEXT-c04.
SELECT-OPTIONS: s_vstel   FOR  likp-vstel.
SELECT-OPTIONS: s_mtart   FOR  lips-mtart OBLIGATORY DEFAULT 'VEHI'.
SELECTION-SCREEN END OF BLOCK orgdata.

SELECTION-SCREEN BEGIN OF BLOCK orddata WITH FRAME TITLE TEXT-c15.
SELECT-OPTIONS: s_ebeln   FOR  lipspo-ponum.
SELECT-OPTIONS: s_ebelp   FOR  lipspo-itmno.
SELECTION-SCREEN END OF BLOCK orddata.

SELECTION-SCREEN BEGIN OF BLOCK create WITH FRAME TITLE TEXT-c10.
SELECT-OPTIONS: s_ernam   FOR  likp-ernam.
SELECT-OPTIONS: s_erdat   FOR  likp-erdat.
SELECTION-SCREEN END OF BLOCK create.

SELECTION-SCREEN BEGIN OF BLOCK timedata WITH FRAME TITLE TEXT-c09.
SELECT-OPTIONS: s_lfdat   FOR  likp-lfdat.
SELECTION-SCREEN END OF BLOCK timedata.



SELECTION-SCREEN BEGIN OF BLOCK partner WITH FRAME TITLE TEXT-c07.
SELECT-OPTIONS: s_lifnr   FOR  likp-lifnr.
SELECTION-SCREEN END OF BLOCK partner.

SELECTION-SCREEN BEGIN OF BLOCK docudata WITH FRAME TITLE TEXT-c08.
SELECT-OPTIONS: s_vbeln   FOR  likp-vbeln MATCHCODE OBJECT vmvm.
SELECT-OPTIONS: s_lifex   FOR  likp-lifex.
SELECTION-SCREEN END OF BLOCK docudata.


SELECTION-SCREEN BEGIN OF BLOCK material WITH FRAME TITLE TEXT-c13.
SELECT-OPTIONS: s_matnr   FOR  lips-matnr MATCHCODE OBJECT mat1. "n_1312200
SELECTION-SCREEN END OF BLOCK material.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: rb_open RADIOBUTTON GROUP rb1.
SELECTION-SCREEN COMMENT 5(10) TEXT-001 FOR FIELD rb_open.
PARAMETERS: rb_close RADIOBUTTON GROUP rb1.
SELECTION-SCREEN COMMENT 20(10) TEXT-002 FOR FIELD rb_close.
PARAMETERS: rb_all RADIOBUTTON GROUP rb1.
SELECTION-SCREEN COMMENT 35(10) TEXT-003 FOR FIELD rb_all.
SELECTION-SCREEN END OF LINE.
